version: '3'

services:
  backend:
    container_name: my-backend
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=todos
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todos
    ports:
      - "3306:3306"
    volumes:
      - mysql_todos_data:/var/lib/mysql

volumes:
  mysql_todos_data:
